<?php
return [
    'db' => [
        'master' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'enter your database',
            'username' => 'enter your username',
            'password' => 'enter your password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'slave01' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'enter your database',
            'username' => 'enter your username',
            'password' => 'enter your password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'slave02' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'enter your database',
            'username' => 'enter your username',
            'password' => 'enter your password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'slave03' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'enter your database',
            'username' => 'enter your username',
            'password' => 'enter your password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'slave04' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'database' => 'enter your database',
            'username' => 'enter your username',
            'password' => 'enter your password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
    ],
];
